server:
  port: 9999

spring:
  application:
    name: userserver
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: userserver

# 配置feign默认最大连接、读取时间
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
