server:
  port: 8761


spring:
  application:
    name: eurekaserver


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-with-eureka: false
    fetch-registry: false
